[phases.setup]
nixPkgs = ["php82", "nginx", "nodejs_18", "npm-9_x", "sqlite"]
nixLibs = ["libmysqlclient", "sqlite.dev"]
nixOverlays = ["https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz"]

[phases.install]
cmds = [
    "mkdir -p /var/log/nginx",
    "mkdir -p /var/cache/nginx",
    "mkdir -p var",
    "composer install --ignore-platform-reqs --no-dev --optimize-autoloader",
    "npm ci"
]

[phases.build]
cmds = [
    "npm run build",
    "php bin/console cache:clear --env=prod --no-debug",
    "php bin/console doctrine:database:create --if-not-exists --env=prod",
    "php bin/console doctrine:migrations:migrate --no-interaction --env=prod"
]

[start]
cmd = "vendor/bin/heroku-php-apache2 public/"