services:
  - type: web
    name: bookme-app
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
      php bin/console doctrine:migrations:migrate --no-interaction --env=prod
      php bin/console cache:clear --env=prod --no-debug
      php bin/console cache:warmup --env=prod
    startCommand: vendor/bin/heroku-php-apache2 public/
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: false
      - key: DATABASE_URL
        value: sqlite:///%kernel.project_dir%/var/data.db