controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api_opinions:
    path: /api/opinions/{encodedName}
    controller: App\Controller\OpinionController::getOpinions
    methods: [POST]